Developed scale for the Hawaii Ocean Health Index on the combined sustainability/risk score for mariculture species in Hawaii. The species that are reported on the State Department of Land and Natural Resources Division of Aquatic Resources that are produced locally for seafood consumption include: Abalone (Haliotus sp), oysters (Crassostrea gigas and Crassostrea sikamea), clams (Venerupis philippinarum), kahala (Seriola dumerili), Pacific White Shrimp (Penaeus vannamei), and limu (Gracilaria sp.). Moi (Pacific Threadfin) is not on the State of Hawaiʻi Department of Agriculture list but it is produced locally for out planting in fishponds. The sustainability of the species produced was assessed as the average of the feed sustainability score (0 protein based, 1 plant based; 0 imported feed, 1 local feed) and the biosecurity risk scored as species status (1 native, 0.75 introduced, or 0 invasive) and the pathogen and virus susceptibility (0 highly susceptible, 0.5 susceptible but preventative measures in place (biosecurity practices such as sterilization and wastewater treatment practices).

#### Reference

[Hawaii OHI](http://ohi-science.org/mhi/)