Resident sentiment scores on the preservation of social and cultural values estimated though HTA visitor sentiment surveys (HTA, 2017). Data available: http://www.hawaiitourismauthority.org/research/reports/evaluation-performance-measures/. Contact for official datasets from the Hawaii Tourism Authority is Jennifer Chun (jennifer@gohta.net). Three questions have been asked consistently and thus have time-series information. Responses to these questions were used to score the sentiment of residents on the benefits and impact of tourism in Hawaiʻi. The three questions were to rate the level of impact and agreement on: 1. Rate the overall impact of tourism on your family, 2. Tourism has brought more benefits than problems, and 3. The island is being run for the tourists at the expense of the local people. The three questions were normalized to a score from 0 to 100 with 100 being positive or agreement on positive impacts of tourism for residence of Hawaiʻi. Questions were averaged and scored to a reference value of 80 as set by the Hawaiʻi Tourism Authority as their target acceptance rate (HTA, 2017).

#### Reference

[HTA](http://www.hawaiitourismauthority.org/research/reports/visitor-satisfaction/)