--- 
title: Layers descriptions 
output: 
  html_document: 
    toc: true 
    toc_depth: 1 
    number_sections: false 
    toc_float: yes 
---

```{r, message=FALSE, echo=FALSE, warning=FALSE, error=FALSE} 
 library(tidyverse) 
 library(knitr) 
 
 layer_meta <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/whi/master/region2017/data_layers_table_wh.csv') 
 layer_path <- 'https://github.com/OHI-Science/whi/tree/master/region2017/layers_whi' 
 
 
```

 
# aquarium fishing 
####[fis_aquarium_catch](https://github.com/OHI-Science/whi/tree/master/region2017/layers_whi/fis_aquarium_catch_whi2018.csv) {-} 
```{r, echo=FALSE, results='hide'}

                                    x <- tempfile(fileext = 'Rmd')

                                    on.exit(unlink(x))

                                    download.file("https://raw.githubusercontent.com/OHI-Science/whi/master/region2017/conf/web/layers_all/fis_aquarium_catch.Rmd", x)
```
 
```{r, child = x, echo=FALSE, results='asis'} 
 
``` 
